server:
  port: 8080
  servlet:
    context-path: /trip
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: gaoyifeng
    url: jdbc:mysql://localhost:3306/trip?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: root
pagehelper:
  reasonable: true
  helper-dialect: mysql
  supportMethodsArguments: true
redis:
  host: 127.0.0.1
  port: 6379
  password: gaoyifeng
  pool:
    max-active: 100
    max-idle: 10
    max-wait: 100000
  timeout: 0