server:
  port: 8080
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: gaoyifeng
    url: jdbc:mysql://localhost:3306/trip?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: root